# Copyright (c) 2025, Unitree Robotics Co., Ltd. All Rights Reserved.
# License: Apache License, Version 2.0

"""Policy adapters used by Unitree benchmark runs."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Protocol

import torch


class BenchmarkPolicy(Protocol):
    name: str

    def reset(self, env, instruction: str) -> None:
        ...

    def act(self, env, observation, step: int) -> torch.Tensor:
        ...


class ZeroActionPolicy:
    """Hold the Unitree robot at its default joint targets."""

    name = "zero"

    def reset(self, env, instruction: str) -> None:
        self.instruction = instruction

    def act(self, env, observation, step: int) -> torch.Tensor:
        return make_zero_action(env)


class ReplayActionPolicy:
    """Replay a JSON action list generated by an external controller."""

    name = "replay"

    def __init__(self, path: str | Path):
        self.path = Path(path)
        with self.path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        self.actions = data.get("actions", data if isinstance(data, list) else [])
        if not isinstance(self.actions, list):
            raise ValueError(f"Replay file {self.path} must contain a list or an 'actions' list.")

    def reset(self, env, instruction: str) -> None:
        self.instruction = instruction

    def act(self, env, observation, step: int) -> torch.Tensor:
        if step < len(self.actions):
            action = torch.as_tensor(self.actions[step], dtype=torch.float32, device=env.device)
            return _shape_action(env, action)
        return make_zero_action(env)


def make_policy(name: str, replay_path: str | None = None) -> BenchmarkPolicy:
    if name == "zero":
        return ZeroActionPolicy()
    if name == "replay":
        if replay_path is None:
            raise ValueError("--replay_path is required when --policy replay is used.")
        return ReplayActionPolicy(replay_path)
    raise ValueError(f"Unsupported benchmark policy '{name}'.")


def make_zero_action(env) -> torch.Tensor:
    action_dim = _action_dim(env)
    return torch.zeros((env.num_envs, action_dim), dtype=torch.float32, device=env.device)


def _action_dim(env) -> int:
    if hasattr(env, "action_manager") and hasattr(env.action_manager, "total_action_dim"):
        return int(env.action_manager.total_action_dim)
    if hasattr(env, "action_space") and getattr(env.action_space, "shape", None):
        shape = env.action_space.shape
        return int(shape[-1])
    return len(env.scene["robot"].data.joint_names)


def _shape_action(env, action: torch.Tensor) -> torch.Tensor:
    action_dim = _action_dim(env)
    action = action.flatten()
    if action.numel() < action_dim:
        padded = torch.zeros(action_dim, dtype=torch.float32, device=env.device)
        padded[: action.numel()] = action
        action = padded
    elif action.numel() > action_dim:
        action = action[:action_dim]
    return action.reshape(env.num_envs, action_dim)
